package com.radix.api;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.radix.api.entities.Cliente;
import com.radix.api.repository.ClienteRespository;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;

@SpringBootApplication
public class RadixTranningJavaProjectApplication implements CommandLineRunner {

	// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	@Autowired 
	private ClienteRespository clienteRepo;
			
	
	public static void main(String[] args) {
		SpringApplication.run(RadixTranningJavaProjectApplication.class, args);
		
	}
	
	@Override
	public void run(String... args) throws Exception{
		
		Cliente clienteAmericanas = new Cliente();
		clienteAmericanas.setCnpj("225399497000135");
		clienteAmericanas.setRazaoSocial("Americanas S.A");
		clienteAmericanas.setDataCriacao(new Date());
		clienteAmericanas.setDataAtualizacao(new Date());
		
		clienteRepo.save(clienteAmericanas);
		
		Cliente clienteMagalu = new Cliente();
		clienteMagalu.setCnpj("2553992270001236");
		clienteMagalu.setRazaoSocial("Magazine Luiza S.A");
		clienteMagalu.setDataCriacao(new Date());
		clienteMagalu.setDataAtualizacao(new Date());
		
		clienteRepo.save(clienteMagalu);
		
			
		Iterable<Cliente> cl = clienteRepo.findAll();
		cl.forEach((c)->{
			System.out.println(c.getId());
			System.out.println(c.getCnpj());
			System.out.println(c.getRazaoSocial());
			
		});
		
		Cliente clienteMag = new Cliente(); 
		clienteMag = clienteRepo.findByCnpj("2553992270001236");
		System.out.println("Consulta por CNPJ");
		System.out.println(clienteMag.getRazaoSocial());
		
		
	}

}
