package com.radix.api;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import com.radix.api.services.ClienteService;


import org.springframework.beans.factory.annotation.Autowired;

@SpringBootApplication
public class RadixTranningJavaProjectApplication implements CommandLineRunner {

	// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	@Autowired 
	private ClienteService clienteService;
			
	
	public static void main(String[] args) {
		SpringApplication.run(RadixTranningJavaProjectApplication.class, args);
		
	}
	
	@Override
	public void run(String... args) throws Exception{
		
		clienteService.inserirCliente();
		clienteService.clientePorCNPJ();
		clienteService.clienteTodos();
		
		
		
	}

}
